/* COACHINGS */
export const GET_COACHINGS = "GET_COACHINGS"
export const GET_COACHINGS_SUCCESS = "GET_COACHINGS_SUCCESS"
export const GET_COACHINGS_FAIL = "GET_COACHINGS_FAIL"

/* COACHINGS DETAIL*/
export const GET_COACHING_DETAIL = "GET_COACHING_DETAIL"
export const GET_COACHING_DETAIL_SUCCESS = "GET_COACHING_DETAIL_SUCCESS"
export const GET_COACHING_DETAIL_FAIL = "GET_COACHING_DETAIL_FAIL"

/**
 * add course
 */
export const ADD_NEW_COACHING = "ADD_NEW_COACHING"
export const ADD_COACHING_SUCCESS = "ADD_COACHING_SUCCESS"
export const ADD_COACHING_FAIL = "ADD_COACHING_FAIL"

/**
 * Edit course
 */
export const UPDATE_COACHING = "UPDATE_COACHING"
export const UPDATE_COACHING_SUCCESS = "UPDATE_COACHING_SUCCESS"
export const UPDATE_COACHING_FAIL = "UPDATE_COACHING_FAIL"

/**
 * Delete course
 */
export const DELETE_COACHING = "DELETE_COACHING"
export const DELETE_COACHING_SUCCESS = "DELETE_COACHING_SUCCESS"
export const DELETE_COACHING_FAIL = "DELETE_COACHING_FAIL"

export const UPDATE_COACHING_LOADING_STATE = "UPDATE_COACHING_LOADING_STATE"
